  services:
   web_service:
     build:
       context: ./
       dockerfile: ./dockerfiles/Dockerfile
     image: kinderneutronimage
     container_name: kinderneutron_container
     stdin_open: true #  docker attach container_id
     tty: true
     ports:
      - "8000:8000"
     volumes:
      - .:/root/kinderneutron
      - ./requirements.txt:/kinderneutron/requirements.txt
   
   psql-db:
    build:
       context: ./
       dockerfile: ./Patches/SQL/Dockerfile
    image: 'postgres:14'
    container_name: psql-db
    environment:
      - PGPASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - '5446:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./Patches/SQL/create-db.sql:/docker-entrypoint-initdb.d/create-db.sql
  volumes:
    db:
      driver: local 